language: node_js
node_js:
  - "stable"
cache: yarn

install:
  - yarn install

script:
  - yarn build

after_success:
  - touch out/.nojekyll

deploy:
  fqdn: www.ranegillian.me
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: out
  target-branch: master
  repo: rgvillanueva28/rgvillanueva28.github.io
  keep-history: true
  on:
    branch: master