language: node_js
node_js:
  - "stable"
cache: yarn

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  target-branch: master
  repo: rgvillanueva28/rgvillanueva28.github.io
  keep-history: true
  on:
    branch: master
